task:
  matrix:
    - name: "Linux - TeX Live 2021"
      container:
        dockerfile: ci/texlive-2021-linux.Dockerfile
      env:
        PROTODIR: proto_tl2016

    - name: "Linux - TeX Live 2020"
      container:
        dockerfile: ci/texlive-2020-linux.Dockerfile
      env:
        PROTODIR: proto_tl2016

    - name: "Linux - TeX Live 2019"
      container:
        dockerfile: ci/texlive-2019-linux.Dockerfile
      env:
        PROTODIR: proto_tl2016

    - name: "Linux - TeX Live 2018"
      container:
        dockerfile: ci/texlive-2018-linux.Dockerfile
      env:
        PROTODIR: proto_tl2016

    - name: "Linux - TeX Live 2017"
      container:
        dockerfile: ci/texlive-2017-linux.Dockerfile
      env:
        PROTODIR: proto_tl2016

    - name: "Linux - TeX Live 2016"
      container:
        dockerfile: ci/texlive-2016-linux.Dockerfile
      env:
        PROTODIR: proto_tl2016

  install_script:
    - pdfinfo -v
    - compare -version
    - gs -v
    - pdflatex -version
    - tlmgr conf
    - make install CONTINUE=y
    - texhash

  test_script:
    - make -C test PYTHON=python3 PROTODIR=${PROTODIR}
