task:
  matrix:
    - name: "Test"
      container:
        dockerfile: ci/texlive-2017.Dockerfile

  install_script:
    - pdfinfo -v
    - compare -version
    - gs -v
    - pdflatex -version
    - tlmgr conf
    - make install CONTINUE=y
    - texhash

  test_script:
    - make -C test
